### ISSUE TITLE
tidy_fields()

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/bibfix#9]
Check for common mistakes in certain fields and correct them, including:

- Abstracts that start with 'Abstract'
- DOIs that include the https://doi.org/
- DOIs that start or end with a non-acceptable character (e.g. '.') caused by copy-paste errors

**Comment by nealhaddaway** [comment]
- Convert titles to Sentence case

**Comment by ryan-carpenter** [comment]
- Unwanted tags and escape characters from xml or html
  - Spaces or tab characters in place of bullet lists
  - &nbsp, &lt, &gt, and so on
  - Trademark and registration symbols
-Missing spaces due to removal of line breaks (e.g., "METHODSWe retrospectively examined …")
- Leading and trailing white space -- trimws()
- Unwanted line breaks, if applicable
  - Most databases collapse abstracts to a single paragraph, but some re-introduce unwanted line breaks by adding copyright data in a new paragraph at the end of the abstract.
  - Sidebar: personally, I like to use the pilcrow sign (¶) to mark paragraph locations that I want to preserve (E.g., "The purpose of this study was … ¶ METHODS: We retrospectively examined … ¶ RESULTS: After a mean of six weeks … ".). I can easily find and replace the pilcrow later, and it makes plain-text abstracts easier to read in the interim.

**Comment by ryan-carpenter** [comment]
>       * &nbsp, &lt, &gt, and so on
>       * Trademark and registration symbols
Covered by repair_language()
